enam/urls.py
from django.urls import path

from . import views

app_name = 'enam'

urlpatterns = [
    path('', views.kegiatan, name='kegiatan'),
    path('savePeserta/', views.savePeserta, name='peserta'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('education', views.education, name='education'),
    path('matkul', views.matkul, name='matkul'),
    path('matkul/<int:id>', 
                       views.matkulDetail,
                       name='detail'),
    path('matkul/<int:id>/delete', 
                       views.hapus,
                       name='hapus'),
]

story8/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as authviews
from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.search, name='search'),
    path('result', views.result, name='result'),
    path('newuser/', views.register, name='register'),
    path('login/', authviews.LoginView.as_view(template_name='story8/login.html'), name='login'),
    path('logout/', authviews.LogoutView.as_view(template_name='story8/search.html'), name='logout'),
]

story_ppw/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('kegiatan/', include('enam.urls')),
    path('accordion/', include('tujuh.urls')),
    path('search/', include('story8.urls')),
]

tujuh/urls.py
from django.urls import path

from . import views

app_name = 'tujuh'

urlpatterns = [
    path('', views.accordion, name='accordion'),
]

enam/models.py
from django.db import models

class KegiatanModel(models.Model):
    nama = models.CharField(max_length=40)

    def __str__(self):
       return self.nama

class PesertaModel(models.Model):
    nama = models.CharField(max_length=50)
    kegiatan = models.ForeignKey(KegiatanModel, on_delete=models.CASCADE)

main/models.py
from django.db import models

class Matkul(models.Model):
    nama = models.TextField()
    dosen = models.TextField()
    deskripsi = models.TextField()
    tahunajar = models.TextField()
    sks = models.IntegerField()
    kelas = models.TextField()

story8/models.py
from django.db import models

# Create your models here.

tujuh/models.py
from django.db import models

# Create your models here.

enam/forms.py
from django.forms import ModelForm
from .models import KegiatanModel, PesertaModel

class BaseForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(BaseForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class Kegiatan_Form(BaseForm):
    class Meta:
        model = KegiatanModel
        fields = ['nama']
    error_messages = {
        'required' : 'Please Type'
    }
    input_attrs = {
        'type' : 'text',
        'placeholder' : 'Nama Kegiatan'
    }

class Peserta_Form(BaseForm):
	class Meta:
		model = PesertaModel
		fields = ['nama', 'kegiatan']
	error_messages = {
		'required' : 'Please Type'
	}
	input_attrs = {
		'type' : 'text'
	}

story8/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class BaseForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(BaseForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class UserRegister(BaseForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

enam/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
from django.shortcuts import redirect
from .forms import Kegiatan_Form, Peserta_Form
from .models import KegiatanModel, PesertaModel

def kegiatan(request):
    form_kegiatan = Kegiatan_Form(request.POST or None)
    form_peserta = Peserta_Form(request.POST or None)

    if (form_kegiatan.is_valid() and  request.method == 'POST' and 'kegiatan' in request.POST):
        form_kegiatan.save()

    variables = {'form_kegiatan': form_kegiatan,
            'form_peserta': form_peserta,
            'kegiatan': KegiatanModel.objects.all(),
            'peserta': PesertaModel.objects.all()}

    return render(request, 'enam/kegiatan.html', variables)

def savePeserta(request):
    form_peserta = Peserta_Form(request.POST or None)
    if (form_peserta.is_valid() and request.method == 'POST' and 'peserta' in request.POST):
        form_peserta.save()

    return redirect('/kegiatan')

main/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Matkul

def home(request):
    return render(request, 'main/home.html')

def education(request):
    return render(request, 'main/education.html')

def matkul(request):
    if request.method == 'POST':
        matkul = Matkul() 
        matkul.nama = request.POST['nama']
        matkul.dosen = request.POST['dosen']
        matkul.deskripsi = request.POST['deskripsi']
        matkul.tahunajar = request.POST['tahunajar']
        matkul.sks = request.POST['sks']
        matkul.kelas = request.POST['kelas']
        matkul.save()
    
    variables = {
        "matkulnya": Matkul.objects.all(),
    }

    return render(request, 'main/matkul.html', variables)

def matkulDetail(request, id):
    matkul = Matkul.objects.get(id=id)
    variables = {
        "matkul" : matkul
    }
    return render(request, 'main/matkulDetails.html', variables)

def hapus(request, id):
    matkul = Matkul.objects.get(id=id)
    matkul.delete()
    return redirect('/matkul')

story8/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
import requests
import json
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib import messages
from .forms import UserRegister

def search(request):
    return render(request, 'story8/search.html', {})

def result(request):
    keyword = request.GET['q']
    url_result = 'https://www.googleapis.com/books/v1/volumes?q=' + keyword
    r = requests.get(url_result)

    data = json.loads(r.content)
    return JsonResponse(data, safe=False)

def register(request):
    if request.method == 'POST':
        form = UserRegister(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, 'Account Succesfully Registered')
            return redirect('/search/login/')
    else:    
        form = UserRegister()
    return render(request, 'story8/register.html', {'form': form})

tujuh/views.py
from django.shortcuts import render

def accordion(request):
    return render(request, 'tujuh/accor.html', {})

enam/templates/enam/kegiatan.html
{% extends 'base.html' %}

{% block meta %}
<title>Kegiatan</title>
{% endblock meta %}

{% block content %}
<body class="bg-light" id="matkul">

    <div class="container">
      <div class="row" style="padding-top: 70px">
        <div class="col-md-4 order-md-1" style="padding-top: 10px; padding-bottom: 20px; padding-right: 30px; border-right: 1px solid #ccc">
            <h3>Tambah Kegiatan</h3>   
            <form method='POST' action="">
            {%csrf_token%}
            <div class="mb-3">
              {{form_kegiatan}}
                <button name="kegiatan" class="btn btn-primary btn-lg btn-block" type="submit">Tambahkan</button>
            </div>
            </form>

            <hr class="mb-4">

            <form method='POST' action="savePeserta/">
            {%csrf_token%}
            <h3>Daftarkan Peserta</h3>
            {{form_peserta}}
            <input value="Daftarkan" name="peserta" class="btn btn-primary btn-lg btn-block" type="submit">
          </form>
        </div>
        
        <div class="col-md-8 order-md-2 mb-4" style="padding-left: 30px">
          <h1>Daftar Kegiatan</h1>
          {% for kegiatanku in kegiatan %}
            <div class="col-md-4">
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                        <th scope="col" style="text-align: center;">{{kegiatanku.nama}}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for orang in peserta%}
                            {%if orang.kegiatan == kegiatanku%}
                            <tr>
                            <td  style="text-align: center;">{{orang.nama}}</td>
                            </tr>
                            {%endif%}
                        {% endfor %}
                        
                    </tbody>
                </table>

            </div>
          {% endfor %}
        </div>
      </div>

      <footer>
        <p> </p>
      </footer>
    </div>
  </body>
{% endblock content %}

main/templates/main/education.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Education</title>
{% endblock meta %}

{% block content %}
    <body id="education">
        <div class="container2">
            <div class="brick">
                <img src="{% static 'img/brick2.jpg' %}" style="100vh">
            </div>
            <div class="decobox2">
                <svg width="70vmax" height="515px">
                <rect x="0" y="0" width="70vmax" height="515px" style="fill:white" />
                </svg>
            </div>
            <div class="textbox2">
                <div class="text2">
                    <div class="EOE" style="font-size: 30px">
                        <p>Education</p>
                    </div>
                    <div class="decobox" style="position: absolute; z-index: -1; padding-top: 160px; padding-left: 420px">
                        <svg width="600px" height="5px">
                            <rect x="0" y="0" width="600px" height="8px" style="fill:#9aedb6" />
                        </svg>
                    </div>
                    <div style= "padding-bottom: 15px">
                        <table>
                            <tr>
                                <td style="font-weight: bold; width: 150px">3rd Semester</td>
                                <td>Fakultas Ilmu Komputer Universitas Indonesia </td>
                            </tr>
                            <tr>
                                <td style="font-weight: bold; width: 150px">2019</td>
                                <td>SMA Negeri 1 Kota Bogor</td>
                            </tr>
                            <tr>
                                <td style="font-weight: bold; width: 150px">2016</td>
                                <td>SMPIT Ummul Quro Bogor</td>
                            </tr>
                            <tr>
                                <td style="font-weight: bold; width: 150px">2013</td>
                                <td>SDIT Aliya Bogor</td>
                            </tr>
                        </table>
                    </div>
                    <div class="EOE" style="font-size: 30px">
                        <p>Organizational Experiences</p>
                    </div>
                    <div class="decobox" style="position: absolute; z-index: -1; padding-top: 305px; padding-left: 420px">
                        <svg width="600px" height="5px">
                            <rect x="0" y="0" width="600px" height="8px" style="fill:#9aedb6" />
                        </svg>
                    </div>
                    <div>
                        <table>
                            <tr>
                                <td style="font-weight: bold; width: 150px">2018</td>
                                <td>english Association for Smansa Youth</td>
                            </tr>
                            <tr>
                                <td style="font-weight: bold; width: 150px">2018</td>
                                <td>DKM Ar-Rahmah</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </body>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>About Me</title>
{% endblock meta %}

{% block content %}
    <body id="home">
        <div class="container">
            <div class="photo">
                <img src="{% static 'img/profile2.jpg' %}" style='max-height: 92vh';>
            </div>
            <div class="textbox">
                <svg width="70vmax" height="87vh">
                <rect x="0" y="0" width="65vmax" height="100%" style="fill:#373741" />
                </svg>
            </div>
            <div class="decobox">
                <svg width="56vmax" height="80px">
                <rect x="0" y="0" width="65vmax" height="1000px" style="fill:#9aedb6" />
                </svg>
            </div>

            <div class="text">
                <div class="name">
                    Zaaf
                </div>
                <div class="name2">
                    <p>Zaafira</p>
                    <p>Rihhadatul'aisy</p>
                    <p>Hendrarto</p>
                </div>
                <div class="subt">
                    <p>1906353946</p>
                    <p>Fasilkom 2019</p>
                </div>
                <div class="desc">
                    <p>Simple. Honest. Diligent.</p>
                </div>
                <div class="interest">
                    <p>Current interest: Web Development</p>
                </div>
            </div>

            <div class="buttons">
                <a class="buttons-space" href="javascript:void(0)" onclick="location.href='https://youtu.be/dQw4w9WgXcQ'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="button" width="70" height="70" viewBox="-144 -144 800 800" role="img" aria-labelledby="instagram-icon">
                        <title>Instagram</title>
                        <path fill="#9aedb6" d="M256 152c-57.9 0-105 47.1-105 105s47.1 105 105 105 105-47.1 105-105-47.1-105-105-105zm0 0c-57.9 0-105 47.1-105 105s47.1 105 105 105 105-47.1 105-105-47.1-105-105-105zM437 0H75C33.6 0 0 33.6 0 75v362c0 41.4 33.6 75 75 75h362c41.4 0 75-33.6 75-75V75c0-41.4-33.6-75-75-75zM256 392c-74.399 0-135-60.601-135-135 0-74.401 60.601-135 135-135s135 60.599 135 135c0 74.399-60.601 135-135 135zm165-270c-16.5 0-30-13.5-30-30s13.5-30 30-30 30 13.5 30 30-13.5 30-30 30zm-165 30c-57.9 0-105 47.1-105 105s47.1 105 105 105 105-47.1 105-105-47.1-105-105-105zm0 0c-57.9 0-105 47.1-105 105s47.1 105 105 105 105-47.1 105-105-47.1-105-105-105zm0 0c-57.9 0-105 47.1-105 105s47.1 105 105 105 105-47.1 105-105-47.1-105-105-105z"></path>
                    </svg>
                </a>
                    <a class="buttons-space" href="javascript:void(0)" onclick="location.href='https://www.linkedin.com/in/zaaf-hend-b5201a1b8/'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="button" width="70" height="70" viewBox="-90 -90 512 512" role="img" aria-labelledby="instagram-icon">
                        <title>LinkedIn</title>
                        <path fill="#9aedb6" d="M72.16 99.73H9.927a5 5 0 0 0-5 5v199.928a5 5 0 0 0 5 5H72.16a5 5 0 0 0 5-5V104.73a5 5 0 0 0-5-5zM41.066.341C18.422.341 0 18.743 0 41.362 0 63.991 18.422 82.4 41.066 82.4c22.626 0 41.033-18.41 41.033-41.038C82.1 18.743 63.692.341 41.066.341zm189.388 94.42c-24.995 0-43.472 10.745-54.679 22.954V104.73a5 5 0 0 0-5-5h-59.599a5 5 0 0 0-5 5v199.928a5 5 0 0 0 5 5h62.097a5 5 0 0 0 5-5V205.74c0-33.333 9.054-46.319 32.29-46.319 25.306 0 27.317 20.818 27.317 48.034v97.204a5 5 0 0 0 5 5H305a5 5 0 0 0 5-5V194.995c0-49.565-9.451-100.234-79.546-100.234z"></path>
                    </svg>
                </a>
            </div>

            <div class="sticky">
            </div>
            
        </div>
    </body>
{% endblock content %}

main/templates/main/matkul.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Mata Kuliah</title>
<link href="../../dist/css/bootstrap.min.css" rel="stylesheet">
{% endblock meta %}

{% block content %}
<body class="bg-light" id="matkul">

    <div class="container">
      <div class="row" style="padding-top: 70px">
        <div class="col-md-8 order-md-2 mb-4">
          <h1>Mata Kuliah</h1>
          <ul class="list-group mb-3">
              {% for matkul in matkulnya %}
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                  <div class="row">
                    <div class="col-md-10 mb-0">
                      <div>
                          <a href="/matkul/{{ matkul.id }}" class="namaMatkul">{{ matkul.nama }}</a>
                          </br>
                          <small class="text-muted">{{ matkul.dosen }}</small>
                      </div>
                      <small class="text-muted">{{ matkul.tahunajar }}</small>
                    </div>

                    <div class="col-md-2 mb-0">
                      <button type="button" class="btn btn-primary hapus" data-toggle="modal" data-target="#{{matkul.id}}">
                      Hapus
                      </button>
                      <!-- Modal -->
                      <div class="modal fade" id="{{matkul.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Apakah Anda yakin ingin menghapus mata kuliah {{matkul.nama}}?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                                <a href="/matkul/{{matkul.id}}/delete" type="button" class="btn btn-primary hapus">Hapus</a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>
              {% endfor %}
          </ul>
        </div>

        <div class="col-md-4 order-md-1" style="padding-top: 10px">
            <h3>Tambah Mata Kuliah</h3>
            <form method='POST' action="matkul">
            {%csrf_token%}

            <div class="mb-3">
              <label>Nama Mata Kuliah</label>
              <input type="text" class="form-control" name='nama' placeholder="" required>
            </div>

            <div class="mb-3">
              <label>Dosen Pengajar</label>
              <input type="text" class="form-control" name='dosen' placeholder="" required>
            </div>

            <div class="mb-3">
              <label>Deskripsi</label>
              <input type="text" class="form-control" name='deskripsi' placeholder="" required>
            </div>

            <div class="mb-3">
              <label>Semester/Tahun</label>
              <input type="text" class="form-control" name='tahunajar' placeholder="Ganjil 2020/2021" required>
            </div>

            <div class="row">
              <div class="col-md-6 mb-3">
                <label>Jumlah SKS</label>
                <input type="number" min="1" max="5" class="form-control" name='sks' placeholder="" required>
              </div>
              <div class="col-md-6 mb-3">
                <label>Ruang Kelas</label>
                <input type="text" class="form-control" name='kelas' placeholder="" required>
              </div>
            </div>

            <hr class="mb-4">
            <button class="btn btn-primary btn-lg btn-block" type="submit">Tambahkan</button>
          </form>
        </div>
      </div>

      <footer>
        <p> </p>
      </footer>
    </div>
  </body>
{% endblock content %}

main/templates/main/matkuldetails.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Mata Kuliah</title>
<link href="../../dist/css/bootstrap.min.css" rel="stylesheet">
{% endblock meta %}

{% block content %}
    <body id="details">
        <div class="container">
            <div class="text">
                <p class="text-muted" style="font-size: 20px"> Nama Mata Kuliah </p>
                <p> {{ matkul.nama }} </p>
                <p class="text-muted" style="font-size: 20px"> Dosen </p>
                <p> {{ matkul.dosen }} </p>
                <p class="text-muted" style="font-size: 20px"> Deskripsi </p>
                <p> {{ matkul.deskripsi }} </p>
                <p class="text-muted" style="font-size: 20px"> Tahun Ajaran </p>
                <p> {{ matkul.tahunajar }} </p>
                <p class="text-muted" style="font-size: 20px"> Jumlah SKS </p>
                <p> {{ matkul.sks }} </p>
                <p class="text-muted" style="font-size: 20px"> Ruangan </p>
                <p> {{ matkul.kelas }} </p>
            </div>
            
        </div>
    </body>
{% endblock content %}

story8/templates/searchBase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Bootstrap & CSS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="shortcut icon" href="#" />
    <link rel="stylesheet" href="{% static 'css/search.css' %}">
    {% block meta %}
    {% endblock meta %}
</head>

<body>
  
  {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
  {% endif %}
    {% block content %}
    {% endblock content %}
    

</body>
</html>

story8/templates/story8/login.html
{% extends "searchBase.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="container">
    <div class="login_form">
        <h1> LOG IN </h1>
        <div class="login_box">
            <div class="container">
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <p class="register-ask">Belum Punya Akun ? <a class ="registhere" href="{% url 'story8:register' %}">REGISTER HERE</a></p>
                <div class="button">
                    <button class="btn btn-dark" type="submit">Login</button>
                </div>
            </form>
        </div>
        </div>
    </div>
</div>
{% endblock content %}

story8/templates/story8/register.html
{% extends "searchBase.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<div class="container">
    <div class="regist_form">
        <h1> REGISTER </h1>
        <div class="regist_box">
            <div class="container">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <p>* required field</p>
                    <div class="button">
                        <button class="btn btn-dark" type="submit">Sign Up</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

story8/templates/story8/search.html
{% load static %}

<html>

    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <link rel="shortcut icon" href="#" />
        <link rel="stylesheet" href="{% static 'css/search.css' %}">
    </head>

    <body>

        <!-- Grey with black text -->
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
            <ul class="navbar-nav">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <p class="nav-text">Welcome, {{user.username}} </p>
                    <a class ="nav-link nav-logout" href="{% url 'story8:logout' %}"> Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'story8:login' %}">Log In</a>
                </li>
            {% endif %}
            </ul>
        </div>
        </nav>

        <div class="container">

            <input class="form-control" id="search" placeholder="Cari Judul Buku">

            <table class="table table-striped">
                <tbody id="result">
                
                </tbody>
            </table>

        </div>

        <script type="text/javascript">

            $(document).ready(function() {
                search("management");

                $("#search").keyup(function() {
                    if ($(this).val() == '') { // check if value changed
                        search("management");
                    } else {
                        search($("#search").val())
                    }
                });
            });

            function search(judul) {
                var url_hasil = '/search/result?q=' + judul;

                $.ajax({
                    url: url_hasil,
                    success: function(result) {

                        var res_obj = $("#result");
                        res_obj.empty();

                        for (i = 0; i < result.items.length; i++) {
                            var book_title = result.items[i].volumeInfo.title;
                            var book_tnails = result.items[i].volumeInfo.imageLinks.smallThumbnail;
                            var book_author_array = result.items[i].volumeInfo.authors;

                            var book_author = (book_author_array == null) ? "" : book_author_array.join(", ");
                            
                            console.log(book_title)
                            console.log(book_tnails)
                            console.log(book_author)

                            res_obj.append('<tr><td align="center"> <img src=' + book_tnails + '> </td>'
                                         + '<td> <div class="title">' + book_title + '</div>'
                                         + '<div class="author text-muted">' + book_author + '</div> </td> </tr>');
                        }
                    }
                });
            }

        </script>

    </body>

</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/stylesheet.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
</body>
  {% include "navbutton.html" %}

  {% block content %}
  {% endblock content %}
</html>

templates/navbutton.html
{% block content %}
    <div class="linkbtn">
        <a class="link-space" href="/">ABOUT ME</a>
        <a class="link-space" href="/education">EDUCATION</a>
        <a class="link-space" href="/matkul">MATA KULIAH</a>
    </div>
{% endblock content %}